name: SemanticRelease

on:
  push:
    branches:
      - "main"

jobs:
  semantic-release:
    name: Create tag if needed
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      with:
        dry_run: true
        extra_plugins: |
          @semantic-release/changelog
          @semantic-release/git
          @semantic-release/github
          @semantic-release/npm
          @semantic-release/exec
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
